### ISSUE TITLE
Problem arise in cbang build in Windows.

### ISSUE THREAD

**Issue by badrik91** [CauldronDevelopmentLLC/CAMotics#246]
Hello Sir,
I have problem in cbang build in windows .I have installed  all package in windows which you given in github .but i face error like this,
![img_20170821_160327_hdr](https://user-images.githubusercontent.com/15092386/29515839-b1e7959e-868b-11e7-8762-680f5d82312a.jpg).
So how can i solve ? is it require new package for this?
Please give solution .

**Comment by jcoffland** [comment]
I made a change that might fix this problem.  Please update your cbang and rebuild both cbang and CAMotics.

If that does not work, since you are getting an error on line 37, then you must be using an old MSVC compiler.  Your compiler appears to be Visual Studio 2013 or older.  I recommend using MSVC 2017.  It's free to download

**Comment by badrik91** [comment]
Hello Sir,
I have faced problem with this two command scons -C CAMotics optimize=1 and scons -C CAMotics package which are given below .How to solve this?
I  have used visual studio  2017 and qt 5.8 .
Please give solution .
![img_20170824_141929_hdr](https://user-images.githubusercontent.com/15092386/29658468-8e296638-88d8-11e7-989a-e5e254ee16a2.jpg)

**Comment by badrik91** [comment]
![img_20170824_143137_hdr](https://user-images.githubusercontent.com/15092386/29658850-0f225294-88da-11e7-9f96-d6af2f02d571.jpg)
this one is second one.

**Comment by jcoffland** [comment]
The first problem is caused by not have ``CBANG_HOME`` set.  The second is caused by not having ``QTDIR`` set.  Or perhaps these environment variables are set but they are set to the wrong location.  See https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/doc/Windows_Build.md

**Comment by badrik91** [comment]
Thank you sir for giving reply.
but i have got this kind of error while run this command scons -C CAMotics package,
![img_20170826_122907_hdr](https://user-images.githubusercontent.com/15092386/29739404-9a9340dc-8a5a-11e7-9832-1be284184b0f.jpg)
how to solve this?
Please give solution.

**Comment by jcoffland** [comment]
If you followed the Windows build instructions then you should have installed NSIS and created a file called ``env.bat`` which added ``c:\Program Files\NSIS\`` to the ``PATH``.  Before running ``scons -C CAMotics package`` you should have run ``env.bat`` in the same console.  Then the build system should be able to find ``makensis`` at ``c:\Program Files\NSIS\makensis.exe``.  If you installed NSIS somewhere else then you will have to adjust your setup accordingly.

It looks like you might be close though.  Can you just run ``CAMotics.exe`` from ``c:\build\CAMotics\CAMotics.exe``?

Why are you building CAMotics from source instead of using the pre built packages at http://camotics.org/download.html?

**Comment by badrik91** [comment]
Thank you Sir,i have completed successfully build  this project in windows .

**Comment by jcoffland** [comment]
Excellent!
