### ISSUE TITLE
Named Subroutines

### ISSUE THREAD

**Issue by nordicxc** [CauldronDevelopmentLLC/CAMotics#256]
Is there any documentation on how to get named subroutines to work? I keep getting errors when trying a simple test. Tried on Windows 7, both x84 and x64 builds.

At first i was getting an "Environment variable GCODE_SCRIPT_PATH not set" error, so I created a User Environment Variable with that name that points to a folder I created at D:\gcode_script. That seemed to hush that error.

I put both of the test programs in that directory (testmain.ngc, and testsub.ngc), and added both of them to the Files list in a CAMotics project.

```
(testmain.ngc)
G90 G20 G17
T1 M06
M03 S18000
G0 X0 Y0
G1 Z-.5 F20
X5 Y5
X0 Y0
o<testsub> call
M2
```

```
(testsub.ngc)
o<testsub> sub
  G0 X-5 Y5
o<testsub> endsub
```

When I go to run the simulation I get the following error(s):
```
ERROR:D:/gcode_script\testmain.ngc:12:0:Failed to open '': Failed to open '': The system cannot find the path specified.
ERROR:: iostream stream error: The system cannot find the path specified.
Tool Path bounds ((0,0,-12.7), (127,127,0)) dimensions (127,127,12.7)
```

Any suggestions would be greatly appreatiated
Thank you for your time and effort

**Comment by jcoffland** [comment]
Part of the problem is that the error message is not very helpful.  The next release of CAMotics will have a better error message.  The other problem is that your GCode program is looking for a file named ``testsub`` but the file is actually called ``testsub.ngc``.

CAMotics attempts to follow LinuxCNC conventions.  Unfortunately, the LinuxCNC documentation is ambiguous.  The documentation says ``To call a separate file with a subroutine name the file the same as your call and include a sub and endsub in the file. . . The file name can include lowercase letters, numbers, dash, and underscore only.``  However, in their example, a comment indicates that the subroutine file is named ``myfile.ngc`` which includes a dot and does not match the subroutine name.  I cannot find where the LinuxCNC docs say anything about subroutine file name extensions.  Are ``.nc`` and ``.gcode`` also valid?

http://linuxcnc.org/docs/html/gcode/o-code.html#ocode:calling-files

If you rename your subroutine file from ``testsub.ngc`` to ``testsub`` it should work in CAMotics.
