### ISSUE TITLE
G53 not properly handled

### ISSUE THREAD

**Issue by WillAdams** [CauldronDevelopmentLLC/CAMotics#328]
Carbide Create now includes a G53 move to safe height as part of its preamble:

(Design File: C:/Users/willa/Desktop/Design_Into_3D-master/box/kerfed/box_imported_top_side.c2d)
(stockMin:0.00mm, 0.00mm, -5.49mm)
(stockMax:609.60mm, 337.01mm, 0.00mm)
(STOCK/BLOCK,609.60, 337.01, 5.49,0.00, 0.00, 5.49)
G90
G21
(Move to safe Z to avoid workholding)
G53G0Z-5.000
(Advanced VCarve Toolpath 1 - Vee)
M05
(TOOL/MILL,0.03, 0.00, 10.00, 15.00)
M6T457
M03S10000
(PREPOSITION FOR RAPID PLUNGE)
G0X46.72Y278.60
Z6.35

the command

G53G0Z-5.000

isn't properly handled in Camotics and one gets a movement through the stock which is disconcerting to say the least.

**Comment by jcoffland** [comment]
The problem is that this code moves in machine coordinates.  CAMotics has no idea what those are because it cannot home the machine and it does not know what offsets were set.

So G54 is handled correctly.  But you'd have to set the same offsets on CAMotics that you have on your machine for it to work as expected.
