### ISSUE TITLE
Using on Fedora 34 with v8-314 rpm package incompatibility

### ISSUE THREAD

**Issue by dpreed** [CauldronDevelopmentLLC/CAMotics#345]
Fedora 34's v8-314 package as distributed has V8_COMPRESS_POINTERS disabled. C! on the other hand, in the source files sets V8_COMPRESS_POINTERS, which causes the camotics command to fail with a notice about incompatible options.

Suggest for source builds that this be made optional in the scons build, and perhaps even be tested prior to building in the SConscript.
Commenting out the #define gave me a working build of camotics, that uses the Fedora distro's v8 package.

**Comment by jcoffland** [comment]
https://github.com/CauldronDevelopmentLLC/cbang/commit/9fc5b9805b6bced027e535c195f377c886fd9f9a makes ``V8_COMPRESS_POINTERS`` optional.  Build with ``scons v8_compress_pointers=0`` to disable it.  It's enabled by default for 64-bit architectures.

Testing for ``V8_COMPRESS_POINTERS`` at build time would be nice but libv8 does not make this easy.  You would have to compile a test program and run it.  I try to avoid compiling and running programs in the configuration phase because it causes problems with cross compiling.  In a cross compile environment, you cannot always run cross-compiled executables.

Ideally libv8 would come with a generated ``v8/config.h`` file that declared the configuration options used to build it.
