### ISSUE TITLE
Python API `get_path()` throws NULL pointer runtime error

### ISSUE THREAD

**Issue by nikcleju** [CauldronDevelopmentLLC/CAMotics#406]
I'm running the Python example (`examples/python/camotics_python_example.py`) using the latest master sources, and I get a NULL pointer error when calling `get_path()`.

```
CAMotics version 1.3.0
Traceback (most recent call last):
  File "/home/ncleju/source/CAMotics/examples/python/camotics_python_example.py", line 342, in <module>
    path = s.get_path()
           ^^^^^^^^^^^^
RuntimeError: Can't dereference NULL pointer!
```

**Comment by bluesun212** [comment]
I believe this issue arose after the commit on Jul 29, 2023, _"Fixed picking, double click on 3D view opens GCode file and at line, …"_.  The issue seems to lie in the `ToolPath::write` function in [src/gcode/ToolPath.cpp](https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/src/gcode/ToolPath.cpp#L105C3-L105C32).  Changing the line `SmartPointer<string> filename;` to `SmartPointer<string> filename = new string();` fixes this issue for me.

**Comment by jcoffland** [comment]
Thanks!
